dom_reproductive_stage:
  - None Seen
  - Floral Bud
  - Open Flower
  - Old Flower
  - Immature Pod
  - Ripe Pod
  - Old Pod

healthy_flowers:
  - 0%
  - 25%
  - 50%
  - More

healthy_pods:
  - 0%
  - 25%
  - 50%
  - More